### ISSUE TITLE
Document timestamp (non)synchronization behaviors 

### ISSUE THREAD

**Issue by chcunningham** [w3c/mediacapture-transform#35]
This issue was originally filed to WebCodecs about VideoTrackReader/Writer, so it should move here now. 
https://github.com/w3c/webcodecs/issues/82

In short, the reporter is asking for sync guarantees where possible and more documentation. The linked chrome bug gives more detail on cases where sync cannot be reasonably guaranteed 
https://bugs.chromium.org/p/chromium/issues/detail?id=1180325

**Comment by padenot** [comment]
I agree with https://bugs.chromium.org/p/chromium/issues/detail?id=1180325#c3, and generally this is what Gecko does. We have the "functional component" discussed in the last paragraph, that allows reclocking audio streams by carefully measuring clock drifts and resampling smoothly so that audio can be piped from a clock domain to another clock domain, with minimal latency. The latency depends on the resampler filter size and the respective render quantum size of the two sides, generally in the order of a few dozen milliseconds for high quality resampling and an output latency of 20-40ms.

**Comment by aboba** [comment]
Along those lines, I have a question relating to timestamp requirements in `MediaStreamTrackGenerator`. Is there an assumption that the `VideoFrame` timestamps are in ascending order?  For example, what happens if an application were to attempt to write a `VideoFrame`with an earlier timestamp than a previously written `VideoFrame`?  Would this result in an error?  The current writeFrame algorithm doesn't say anything about this.

**Comment by guidou** [comment]
> Along those lines, I have a question relating to timestamp requirements in `MediaStreamTrackGenerator`. Is there an assumption that the `VideoFrame` timestamps are in ascending order? For example, what happens if an application were to attempt to write a `VideoFrame`with an earlier timestamp than a previously written `VideoFrame`? Would this result in an error? The current writeFrame algorithm doesn't say anything about this.

There is no such assumption. The frames are passed to the sinks and the sinks decide what to do with those frames.

**Comment by alvestrand** [comment]
Back in the dawn of time, it was assumed that if two tracks were added to the same MediaStream (not Stream), the platform would attempt to synchronize the playout according to their timestamps - but we explicitly stayed away from guaranteeing that we could.

**Comment by alvestrand** [comment]
My "feel" for this problem is that MSTP and VTG need to be able to pass timestamps they are given unmodified. Synchronizaton needs to be dealt with by having the different tracks produce consistent timestamps - but that's a MediaStreamTrack problem, not a transform problem.

Closing this as irrelevant to the transform spec (but relevant to the larger context of "how do we build systems out of these tools").
